#!/bin/bash

echo "ULAKNET Network - Python 3 Host Command Examples"
echo "==============================================="
echo ""
echo "For single hosts:"
echo "  h1 python3 -m http.server 80"
echo "  h1 ifconfig"
echo "  h1 ping -c3 h2"
echo ""
echo "For running a command on one host and accessing from another:"
echo "  Use two separate Mininet CLI commands:"
echo "  h1 python3 -m http.server 80 &"
echo "  h2 wget -O- http://10.0.0.1:80"
echo ""
echo "To test connectivity, use direct IPs:"
echo "  h1 ping -c3 10.0.0.4"
echo ""
echo "Useful debugging commands:"
echo "  sh ovs-ofctl dump-flows s1"
echo "  sh ovs-vsctl show"
echo "  h1 route -n"
echo "  links"
echo ""
echo "Note: For Python 2 use 'SimpleHTTPServer', for Python 3 use 'http.server'"
