#!/bin/bash

echo "ULAKNET Mininet Commands"
echo "======================="
echo ""
echo "# Test basic connectivity:"
echo "h1 ping -c3 h4"
echo ""
echo "# Test bandwidth using iperf:"
echo "h1 iperf -s &"
echo "h4 iperf -c h1"
echo ""
echo "# Run a web server and access it:"
echo "h1 python -m http.server 80 &"
echo "h4 wget -O- h1:80"
echo ""
echo "# Run traceroute (if installed):"
echo "h1 traceroute -n h16"
echo ""
echo "# Using two separate commands:"
echo "h1 python -m http.server 80 &"
echo "h19 wget -O- h1:80"
echo ""
echo "# Or run command on specific host from Mininet:"
echo "h1 ping h4"
echo ""
echo "# Check if routes are properly set:"
echo "h1 route -n"
echo "h4 route -n"
