#!/bin/bash

echo "ULAKNET Network Topology - Connectivity Test Script"
echo "=================================================="
echo ""
echo "This script generates Mininet commands to test connectivity."
echo "Copy and paste these commands into the Mininet CLI."
echo ""
echo "# First, ensure the controller is working:"
echo "sh ovs-vsctl show | grep is_connected"
echo ""
echo "# Enable spanning tree protocol on all switches to prevent loops:"
echo "sh for s in s1 s2 s3 s4 s5 s6 s7 s8 s9 s10 s11 s12 s13 s14 s15 s16 s17 s18 s19; do ovs-vsctl set bridge \$s stp_enable=true; done"
echo ""
echo "# Test connectivity between Ankara hosts:"
echo "h1 ping -c3 h2"
echo "h1 ping -c3 h3"
echo ""
echo "# Test connectivity between Ankara and Istanbul:"
echo "h1 ping -c3 h4"
echo "h2 ping -c3 h5"
echo ""
echo "# Test connectivity between Istanbul and Izmir:"
echo "h4 ping -c3 h7"
echo ""
echo "# Check routes on hosts:"
echo "h1 route -n"
echo "h4 route -n"
echo "h16 route -n"
echo ""
echo "# Try to find a path using traceroute:"
echo "h1 traceroute -n h16"
echo ""
echo "# Test more connections:"
echo "h1 ping -c3 h19  # Ankara to Diyarbakir"
echo ""
echo "# Set up static routes if needed:"
echo "h1 ip route add 10.0.0.16/32 via 10.0.0.1"
echo "h16 ip route add 10.0.0.1/32 via 10.0.0.1"
echo ""
echo "# Try iperf after setting routes:"
echo "iperf h1 h16"
