#!/bin/bash

echo "ULAKNET Network - Test Commands Guide"
echo "===================================="
echo ""
echo "Copy and paste these commands into the Mininet CLI to test network functionality:"
echo ""
echo "1. Basic network information:"
echo "   nodes           # Show all nodes"
echo "   net             # Show network connections"
echo "   links           # Show network links and their status"
echo ""
echo "2. Connectivity testing:"
echo "   pingall         # Test connectivity between all hosts"
echo "   pingallfull     # Detailed ping test between all hosts"
echo ""
echo "3. Bandwidth testing:"
echo "   # Test bandwidth between Ankara and Istanbul:"
echo "   iperf h1 h4"
echo ""
echo "   # Test bandwidth between Istanbul and Izmir:"
echo "   iperf h4 h7"
echo ""
echo "   # Test bandwidth between distant nodes (Ankara-Erzurum):"
echo "   iperf h1 h16"
echo ""
echo "4. Path discovery:"
echo "   # Trace route from Ankara to Van:"
echo "   h1 traceroute h16"
echo ""
echo "   # Check the path from Istanbul to Diyarbakir:"
echo "   h4 traceroute h19"
echo ""
echo "5. Advanced testing:"
echo "   # Run a web server on h1 and access it from h19:"
echo "   h1 python -m SimpleHTTPServer 80 &"
echo "   h19 wget -O- h1"
echo ""
echo "   # Test multiple flows with varying delays:"
echo "   h1 ping h4 &"
echo "   h7 ping h16 &"
echo "   h3 ping h12 &"
echo ""
echo "6. Exit Mininet:"
echo "   quit           # Exit Mininet CLI and clean up"
echo ""
echo "For more commands, type 'help' at the Mininet CLI prompt"
